import chunk from 'lodash/chunk';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useMemo } from 'react';
import styles from '../styles/Home.module.css';

interface Tag {
  title: 'Catalogue' | 'Special';
  brand: string;
  description: string;
  size: string;
  price: string;
  saving: string;
  endDate: string;
  barcode: number;
  quantity?: number;
}

const data: Tag[] = [
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
];

const Home: NextPage = () => {
  const chunkedData = chunk(data, 9);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {chunkedData.map((page) => (
          <section className={styles.page}>
            {page.map((tag) => (
              <div className={styles.tag}>
                <span className={styles.title}>{tag.title}</span>
                <span className={styles.brand}>{tag.brand}</span>
                <span className={styles.description}>{tag.description}</span>
                <span className={styles.size}>{tag.size}</span>
                <span className={styles.price}>{tag.price}</span>
                <span className={styles.saving}>
                  Save <span>{tag.saving}</span>{' '}
                  <span className={styles.savingSubtext}>off RRP</span>
                </span>
                <span className={styles.endDate}>
                  Sale ends <span>{tag.endDate}</span>
                </span>
                <span className={styles.barcode}>{tag.barcode}</span>
              </div>
            ))}
          </section>
        ))}
      </main>
    </div>
  );
};

export default Home;
