import chunk from 'lodash/chunk';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Tag } from '../components';
import styles from '../styles/Home.module.css';

const data: Tag[] = [
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
];

const Home: NextPage = () => {
  const chunkedData = chunk(data, 9);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {chunkedData.map((page) => (
          <section className={styles.page}>
            {page.map((tag) => (
              <Tag {...tag} />
            ))}
          </section>
        ))}
      </main>
    </div>
  );
};

export default Home;
