import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

interface Tag {
  title: 'Catalogue' | 'Special';
  brand: string;
  description: string;
  size: string;
  price: string;
  saving: string;
  endDate: string;
  barcode: number;
  quantity?: number;
}

const data: Tag[] = [
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
  {
    title: 'Catalogue',
    brand: 'Blackmores',
    description: 'Bio C 1000mg',
    size: '10 tablets',
    price: '$4.84',
    saving: '$4.16',
    endDate: 'August 28',
    barcode: 9300807326022,
  },
];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.page}>
          {data.map((tag) => (
            <div className={styles.tag}>
              <span className={styles.title} contentEditable>
                {tag.title}
              </span>
              <span className={styles.brand} contentEditable>
                {tag.brand}
              </span>
              <span className={styles.description} contentEditable>
                {tag.description}
              </span>
              <span className={styles.size} contentEditable>
                {tag.size}
              </span>
              <span className={styles.price} contentEditable>
                {tag.price}
              </span>
              <span className={styles.saving}>
                Save <span contentEditable>{tag.saving}</span>{' '}
                <span className={styles.savingSubtext}>off RRP</span>
              </span>
              <span className={styles.endDate}>
                Sale ends <span contentEditable>{tag.endDate}</span>
              </span>
              <span className={styles.barcode} contentEditable>
                {tag.barcode}
              </span>
            </div>
          ))}
        </section>
      </main>
    </div>
  );
};

export default Home;
